# Generated by Django 2.1.5 on 2019-01-13 02:30

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcmngt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcflow',
            name='description',
            field=markdownx.models.MarkdownxField(help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalfuncflow',
            name='description',
            field=markdownx.models.MarkdownxField(help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalsubfuncflow',
            name='description',
            field=markdownx.models.MarkdownxField(help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subfuncflow',
            name='description',
            field=markdownx.models.MarkdownxField(help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", null=True, verbose_name='Description'),
        ),
    ]
