# Generated by Django 2.1.4 on 2019-01-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcmngt', '0002_auto_20190113_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfuncflow',
            name='func_flow',
            field=models.ForeignKey(default=None, limit_choices_to={'status__in': ('On going', 'Released')}, on_delete=django.db.models.deletion.PROTECT, related_name='subfuncflow_flow', to='funcmngt.FuncFlow', verbose_name='Functional Flow'),
        ),
        migrations.AlterField(
            model_name='subfuncflow',
            name='receiver',
            field=models.ForeignKey(default=None, limit_choices_to={'status__in': ('On going', 'Released')}, on_delete=django.db.models.deletion.PROTECT, related_name='subfuncflow_rec_app', to='appmngt.Application', verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='subfuncflow',
            name='requester',
            field=models.ForeignKey(default=None, limit_choices_to={'status__in': ('On going', 'Released')}, on_delete=django.db.models.deletion.PROTECT, related_name='subfuncflow_req_app', to='appmngt.Application', verbose_name='Requester'),
        ),
    ]
