# Generated by Django 2.1.4 on 2019-01-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcmngt', '0004_auto_20190114_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcflow',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='Pin'),
        ),
        migrations.AddField(
            model_name='historicalfuncflow',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='Pin'),
        ),
        migrations.AddField(
            model_name='historicalsubfuncflow',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='Pin'),
        ),
        migrations.AddField(
            model_name='subfuncflow',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='Pin'),
        ),
    ]
