# Generated by Django 2.1.4 on 2019-01-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcmngt', '0005_auto_20190116_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcflow',
            options={'ordering': ['-pin', 'name'], 'verbose_name': 'Functional flow'},
        ),
        migrations.AlterModelOptions(
            name='subfuncflow',
            options={'ordering': ['-pin', 'name'], 'verbose_name': 'Sub functional flow'},
        ),
        migrations.AlterField(
            model_name='funcflow',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='historicalfuncflow',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='historicalsubfuncflow',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='subfuncflow',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
    ]
