# Generated by Django 2.1.4 on 2018-12-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('appmngt', '0002_auto_20181218_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='historicalenvironment',
            name='gateway',
        ),
        migrations.AddField(
            model_name='environment',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='environment',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='historicalenvironment',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='historicalenvironment',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
