# Generated by Django 2.1.5 on 2019-01-13 02:30

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmngt', '0002_auto_20190104_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=markdownx.models.MarkdownxField(help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='application',
            name='partner',
            field=models.ForeignKey(default=None, limit_choices_to={'status__in': ('On going', 'Released')}, on_delete=django.db.models.deletion.PROTECT, related_name='app_partner', to='appmngt.Partner', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='application',
            name='univers',
            field=models.ForeignKey(default=None, limit_choices_to={'status__in': ('On going', 'Released')}, on_delete=django.db.models.deletion.PROTECT, related_name='app_univers', to='appmngt.Univers', verbose_name='Univers'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='application',
            field=models.ForeignKey(default=None, limit_choices_to={'status__in': ('On going', 'Released')}, on_delete=django.db.models.deletion.PROTECT, related_name='env_app', to='appmngt.Application', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='description',
            field=markdownx.models.MarkdownxField(help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='description',
            field=markdownx.models.MarkdownxField(help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalenvironment',
            name='description',
            field=markdownx.models.MarkdownxField(help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalpartner',
            name='description',
            field=markdownx.models.MarkdownxField(help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalrelease',
            name='description',
            field=markdownx.models.MarkdownxField(help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalunivers',
            name='description',
            field=markdownx.models.MarkdownxField(help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=markdownx.models.MarkdownxField(help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='release',
            name='description',
            field=markdownx.models.MarkdownxField(help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='univers',
            name='description',
            field=markdownx.models.MarkdownxField(help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", null=True, verbose_name='Description'),
        ),
    ]
