# Generated by Django 2.1.4 on 2018-12-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmngt', '0003_auto_20181218_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='content_type',
            field=models.ForeignKey(default=None, limit_choices_to={'model__in': ('gatewayws', 'gatewaycft')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='historicalenvironment',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, limit_choices_to={'model__in': ('gatewayws', 'gatewaycft')}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.ContentType'),
        ),
    ]
