# Generated by Django 2.1.4 on 2018-12-18 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techmngt', '0001_initial'),
        ('appmngt', '0004_auto_20181218_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='historicalenvironment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='historicalenvironment',
            name='object_id',
        ),
        migrations.AddField(
            model_name='environment',
            name='gateway',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='env_gatway', to='techmngt.Gateway', verbose_name='Gateway'),
        ),
        migrations.AddField(
            model_name='historicalenvironment',
            name='gateway',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='techmngt.Gateway', verbose_name='Gateway'),
        ),
    ]
