# Generated by Django 2.1.4 on 2018-12-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmngt', '0001_initial'),
        ('appmngt', '0005_auto_20181218_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='historicalenvironment',
            name='gateway',
        ),
        migrations.AddField(
            model_name='environment',
            name='gateways',
            field=models.ManyToManyField(blank=True, default=None, related_name='env_gatway', to='techmngt.Gateway', verbose_name='Gateways'),
        ),
    ]
