# Generated by Django 2.1.4 on 2019-01-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmngt', '0005_auto_20190116_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-pin', 'name'], 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='environment',
            options={'ordering': ['-pin', 'name'], 'verbose_name_plural': 'Environments'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-pin', 'name'], 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-pin', 'name'], 'verbose_name_plural': 'Releases'},
        ),
        migrations.AlterModelOptions(
            name='univers',
            options={'ordering': ['-pin', 'name'], 'verbose_name_plural': 'Univers'},
        ),
        migrations.AddField(
            model_name='environment',
            name='type',
            field=models.CharField(choices=[('Dev', 'Dev'), ('Test', 'Test'), ('Live', 'Live')], default='Dev', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalenvironment',
            name='type',
            field=models.CharField(choices=[('Dev', 'Dev'), ('Test', 'Test'), ('Live', 'Live')], default='Dev', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='historicalenvironment',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='historicalpartner',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='historicalrelease',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='historicalunivers',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='release',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='univers',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
    ]
