# Generated by Django 2.1.4 on 2019-01-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmngt', '0006_auto_20190117_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='type',
            field=models.CharField(choices=[('Dev', 'Dev'), ('Integration', 'Integration'), ('Test', 'Test'), ('Pre-production', 'Pre-production'), ('Production', 'Production')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalenvironment',
            name='type',
            field=models.CharField(choices=[('Dev', 'Dev'), ('Integration', 'Integration'), ('Test', 'Test'), ('Pre-production', 'Pre-production'), ('Production', 'Production')], max_length=20),
        ),
    ]
