# Generated by Django 2.1.4 on 2019-01-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmngt', '0007_auto_20190117_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='type',
            field=models.IntegerField(choices=[(0, 'Dev'), (1, 'Integration'), (2, 'Test'), (3, 'Pre-production'), (4, 'Production')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalenvironment',
            name='type',
            field=models.IntegerField(choices=[(0, 'Dev'), (1, 'Integration'), (2, 'Test'), (3, 'Pre-production'), (4, 'Production')], default=0),
        ),
    ]
