# Generated by Django 2.1.4 on 2019-01-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmngt', '0008_auto_20190117_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='type',
            field=models.CharField(choices=[('Dev', (('0', 'Dev'),)), ('Project', (('1', 'Integration'), ('2', 'Test'))), ('3', 'Pre-production'), ('4', 'Production')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalenvironment',
            name='type',
            field=models.CharField(choices=[('Dev', (('0', 'Dev'),)), ('Project', (('1', 'Integration'), ('2', 'Test'))), ('3', 'Pre-production'), ('4', 'Production')], max_length=10),
        ),
    ]
