version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver --verbosity 3  0.0.0.0:8000
    stdin_open: true
    tty: true
    image: groovy
    volumes:
      - .:/groovy
    ports:
      - "8000:8000"
    depends_on:
      - db