# Generated by Django 2.1.4 on 2018-12-18 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techmngt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnetworkflow',
            name='destination_gateway',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='techmngt.Gateway', verbose_name='Destination gateway'),
        ),
        migrations.AddField(
            model_name='historicalnetworkflow',
            name='source_gateway',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='techmngt.Gateway', verbose_name='Source gateway'),
        ),
        migrations.AddField(
            model_name='networkflow',
            name='destination_gateway',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_gateway_env', to='techmngt.Gateway', verbose_name='Destination gateway'),
        ),
        migrations.AddField(
            model_name='networkflow',
            name='source_gateway',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_gateway_env', to='techmngt.Gateway', verbose_name='Source gateway'),
        ),
    ]
