# Generated by Django 2.1.4 on 2018-12-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmngt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnetworkflow',
            name='destination_ip',
        ),
        migrations.RemoveField(
            model_name='historicalnetworkflow',
            name='source_ip',
        ),
        migrations.RemoveField(
            model_name='networkflow',
            name='destination_ip',
        ),
        migrations.RemoveField(
            model_name='networkflow',
            name='source_ip',
        ),
        migrations.AddField(
            model_name='historicalserver',
            name='dns',
            field=models.CharField(blank=True, max_length=512, verbose_name='DNS'),
        ),
        migrations.AddField(
            model_name='historicalserver',
            name='ip',
            field=models.CharField(blank=True, max_length=64, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='server',
            name='dns',
            field=models.CharField(blank=True, max_length=512, verbose_name='DNS'),
        ),
        migrations.AddField(
            model_name='server',
            name='ip',
            field=models.CharField(blank=True, max_length=64, verbose_name='IP'),
        ),
    ]
