# Generated by Django 2.1.4 on 2018-12-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmngt', '0002_auto_20181218_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='protocol',
        ),
        migrations.AddField(
            model_name='gatewaycft',
            name='protocol',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to={'type': 'Asynchronous'}, to='techmngt.Protocol', verbose_name='Protocol'),
        ),
        migrations.AddField(
            model_name='gatewayws',
            name='protocol',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to={'type': 'Synchronous'}, to='techmngt.Protocol', verbose_name='Protocol'),
        ),
    ]
