# Generated by Django 2.1.4 on 2019-01-14 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techmngt', '0002_auto_20190113_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynchronousflow',
            name='protocol',
            field=models.ForeignKey(limit_choices_to={'status__in': ('On going', 'Released'), 'type': 'Asynchronous'}, on_delete=django.db.models.deletion.PROTECT, related_name='asynchronousflow_protocol', to='techmngt.Protocol', verbose_name='Protocol'),
        ),
        migrations.AlterField(
            model_name='historicalbatchflow',
            name='subfunc_flow',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, limit_choices_to={'status__in': ('On going', 'Released')}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='funcmngt.SubFuncFlow', verbose_name='Sub Functional Flow'),
        ),
        migrations.AlterField(
            model_name='historicaltechflow',
            name='subfunc_flow',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, limit_choices_to={'status__in': ('On going', 'Released')}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='funcmngt.SubFuncFlow', verbose_name='Sub Functional Flow'),
        ),
        migrations.AlterField(
            model_name='historicaluriflow',
            name='subfunc_flow',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, limit_choices_to={'status__in': ('On going', 'Released')}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='funcmngt.SubFuncFlow', verbose_name='Sub Functional Flow'),
        ),
        migrations.AlterField(
            model_name='techflow',
            name='subfunc_flow',
            field=models.OneToOneField(default=None, limit_choices_to={'status__in': ('On going', 'Released')}, on_delete=django.db.models.deletion.PROTECT, related_name='techflow_subflow', to='funcmngt.SubFuncFlow', verbose_name='Sub Functional Flow'),
        ),
    ]
