# Generated by Django 2.1.4 on 2019-01-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techmngt', '0003_auto_20190114_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkflow',
            name='destination_server',
            field=models.ForeignKey(default=None, limit_choices_to={'status__in': ('On going', 'Released')}, on_delete=django.db.models.deletion.PROTECT, related_name='destination_server_env', to='techmngt.Server', verbose_name='Destination server'),
        ),
        migrations.AlterField(
            model_name='networkflow',
            name='source_server',
            field=models.ForeignKey(default=None, limit_choices_to={'status__in': ('On going', 'Released')}, on_delete=django.db.models.deletion.PROTECT, related_name='source_server_env', to='techmngt.Server', verbose_name='Source server'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.OneToOneField(default=None, limit_choices_to={'status__in': ('On going', 'Released')}, on_delete=django.db.models.deletion.PROTECT, related_name='server_servertype', to='techmngt.ServerType', verbose_name='Server Type'),
        ),
    ]
