# Generated by Django 2.1.4 on 2019-01-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmngt', '0006_historicalsynchronousflow_synchronousflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronousflow',
            name='servers',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to={'status__in': ('On going', 'Released')}, related_name='sync_servers', to='techmngt.Server', verbose_name='Servers'),
        ),
        migrations.AddField(
            model_name='uriflow',
            name='servers',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to={'status__in': ('On going', 'Released')}, related_name='uri_servers', to='techmngt.Server', verbose_name='Servers'),
        ),
    ]
