# Generated by Django 2.1.4 on 2019-01-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techmngt', '0007_auto_20190115_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.ForeignKey(default=None, limit_choices_to={'status__in': ('On going', 'Released')}, on_delete=django.db.models.deletion.PROTECT, related_name='server_servertype', to='techmngt.ServerType', verbose_name='Server Type'),
        ),
    ]
