# Generated by Django 2.1.4 on 2019-01-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmngt', '0009_auto_20190116_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynchronousflow',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='Pin'),
        ),
        migrations.AddField(
            model_name='historicalasynchronousflow',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='Pin'),
        ),
        migrations.AddField(
            model_name='historicalbatchflow',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='Pin'),
        ),
        migrations.AddField(
            model_name='historicalnetworkflow',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='Pin'),
        ),
        migrations.AddField(
            model_name='historicalserver',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='Pin'),
        ),
        migrations.AddField(
            model_name='historicalsynchronousflow',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='Pin'),
        ),
        migrations.AddField(
            model_name='historicaltechflow',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='Pin'),
        ),
        migrations.AddField(
            model_name='historicaluriflow',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='Pin'),
        ),
        migrations.AddField(
            model_name='networkflow',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='Pin'),
        ),
        migrations.AddField(
            model_name='server',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='Pin'),
        ),
        migrations.AddField(
            model_name='techflow',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='Pin'),
        ),
    ]
