# Generated by Django 2.1.4 on 2019-01-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmngt', '0010_auto_20190116_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asynchronousflow',
            options={'ordering': ['-pin', 'name'], 'verbose_name_plural': 'Asynchronous Flows'},
        ),
        migrations.AlterModelOptions(
            name='batchflow',
            options={'ordering': ['-pin', 'name'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='networkflow',
            options={'ordering': ['-pin', 'name'], 'verbose_name': 'Network flow', 'verbose_name_plural': 'Network flows'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['-pin', 'name'], 'verbose_name_plural': 'Servers'},
        ),
        migrations.AlterModelOptions(
            name='synchronousflow',
            options={'ordering': ['-pin', 'name'], 'verbose_name': 'Synchronous', 'verbose_name_plural': 'Synchronous'},
        ),
        migrations.AlterModelOptions(
            name='techflow',
            options={'ordering': ['-pin', 'name'], 'verbose_name': 'Technical flow'},
        ),
        migrations.AlterModelOptions(
            name='uriflow',
            options={'ordering': ['-pin', 'name'], 'verbose_name': 'URI', 'verbose_name_plural': 'URI'},
        ),
        migrations.AlterField(
            model_name='asynchronousflow',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='historicalasynchronousflow',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='historicalbatchflow',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkflow',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='historicalserver',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='historicalsynchronousflow',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='historicaltechflow',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='historicaluriflow',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='networkflow',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='server',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='techflow',
            name='pin',
            field=models.BooleanField(default=False, help_text='Keep on top', verbose_name='Pin'),
        ),
    ]
