# Generated by Django 2.1.5 on 2019-01-04 23:06

import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appmngt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Phone number')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('web_site', models.URLField(blank=True, verbose_name='Web site')),
                ('street', models.TextField(blank=True, verbose_name='street')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='city')),
                ('province', models.CharField(blank=True, max_length=200, verbose_name='province')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postal code')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=200, verbose_name='last name')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical person',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTeam',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Phone number')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('web_site', models.URLField(blank=True, verbose_name='Web site')),
                ('street', models.TextField(blank=True, verbose_name='street')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='city')),
                ('province', models.CharField(blank=True, max_length=200, verbose_name='province')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postal code')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('departement', models.CharField(max_length=100, verbose_name='Department')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, default=None, limit_choices_to={'status__in': ('On going', 'Released')}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appmngt.Partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'historical team',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Phone number')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('web_site', models.URLField(blank=True, verbose_name='Web site')),
                ('street', models.TextField(blank=True, verbose_name='street')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='city')),
                ('province', models.CharField(blank=True, max_length=200, verbose_name='province')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postal code')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=200, verbose_name='last name')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Phone number')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('web_site', models.URLField(blank=True, verbose_name='Web site')),
                ('street', models.TextField(blank=True, verbose_name='street')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='city')),
                ('province', models.CharField(blank=True, max_length=200, verbose_name='province')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postal code')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('departement', models.CharField(max_length=100, verbose_name='Department')),
                ('partner', models.ForeignKey(blank=True, default=None, limit_choices_to={'status__in': ('On going', 'Released')}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_partner', to='appmngt.Partner', verbose_name='Partner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='person_team', to='contactmngt.Team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='team',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contactmngt.Team', verbose_name='Team'),
        ),
    ]
