# Generated by Django 2.1.4 on 2019-01-14 15:47

from django.db import migrations, models
import django_cryptography.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contactmngt', '0002_auto_20190114_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='about',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='about')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='city',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='city')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='country',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, verbose_name='country')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='email_address',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=254, verbose_name='email address')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, verbose_name='first name')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200, verbose_name='last name')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='phone_number',
            field=django_cryptography.fields.encrypt(phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Phone number')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='postal_code',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=10, verbose_name='postal code')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='province',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='province')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='street',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='street')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='web_site',
            field=django_cryptography.fields.encrypt(models.URLField(blank=True, verbose_name='Web site')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='about',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='about')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='city',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='city')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='country',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, verbose_name='country')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='departement',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, verbose_name='Department')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='email_address',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=254, verbose_name='email address')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, verbose_name='Name')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='phone_number',
            field=django_cryptography.fields.encrypt(phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Phone number')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='postal_code',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=10, verbose_name='postal code')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='province',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='province')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='street',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='street')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='web_site',
            field=django_cryptography.fields.encrypt(models.URLField(blank=True, verbose_name='Web site')),
        ),
        migrations.AlterField(
            model_name='person',
            name='about',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='about')),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='city')),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, verbose_name='country')),
        ),
        migrations.AlterField(
            model_name='person',
            name='email_address',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=254, verbose_name='email address')),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, verbose_name='first name')),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200, verbose_name='last name')),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=django_cryptography.fields.encrypt(phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Phone number')),
        ),
        migrations.AlterField(
            model_name='person',
            name='postal_code',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=10, verbose_name='postal code')),
        ),
        migrations.AlterField(
            model_name='person',
            name='province',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='province')),
        ),
        migrations.AlterField(
            model_name='person',
            name='street',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='street')),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='person',
            name='web_site',
            field=django_cryptography.fields.encrypt(models.URLField(blank=True, verbose_name='Web site')),
        ),
        migrations.AlterField(
            model_name='team',
            name='about',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='about')),
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='city')),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, verbose_name='country')),
        ),
        migrations.AlterField(
            model_name='team',
            name='departement',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, verbose_name='Department')),
        ),
        migrations.AlterField(
            model_name='team',
            name='email_address',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=254, verbose_name='email address')),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, verbose_name='Name')),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone_number',
            field=django_cryptography.fields.encrypt(phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Phone number')),
        ),
        migrations.AlterField(
            model_name='team',
            name='postal_code',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=10, verbose_name='postal code')),
        ),
        migrations.AlterField(
            model_name='team',
            name='province',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='province')),
        ),
        migrations.AlterField(
            model_name='team',
            name='street',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='street')),
        ),
        migrations.AlterField(
            model_name='team',
            name='web_site',
            field=django_cryptography.fields.encrypt(models.URLField(blank=True, verbose_name='Web site')),
        ),
    ]
