# Generated by Django 2.1.4 on 2019-01-14 17:07

from django.db import migrations, models
import django_cryptography.fields
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmngt', '0003_auto_20190114_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='about',
            field=django_cryptography.fields.encrypt(markdownx.models.MarkdownxField(blank=True, help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", verbose_name='About')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='city',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='City')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='country',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, verbose_name='Country')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='email_address',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, verbose_name='First name')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200, verbose_name='Last name')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='postal_code',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=10, verbose_name='Postal code')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='province',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='Province')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='street',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='Street')),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='Title')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='about',
            field=django_cryptography.fields.encrypt(markdownx.models.MarkdownxField(blank=True, help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", verbose_name='About')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='city',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='City')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='country',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, verbose_name='Country')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='email_address',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='postal_code',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=10, verbose_name='Postal code')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='province',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='Province')),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='street',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='Street')),
        ),
        migrations.AlterField(
            model_name='person',
            name='about',
            field=django_cryptography.fields.encrypt(markdownx.models.MarkdownxField(blank=True, help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", verbose_name='About')),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='City')),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, verbose_name='Country')),
        ),
        migrations.AlterField(
            model_name='person',
            name='email_address',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, verbose_name='First name')),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200, verbose_name='Last name')),
        ),
        migrations.AlterField(
            model_name='person',
            name='postal_code',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=10, verbose_name='Postal code')),
        ),
        migrations.AlterField(
            model_name='person',
            name='province',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='Province')),
        ),
        migrations.AlterField(
            model_name='person',
            name='street',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='Street')),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='Title')),
        ),
        migrations.AlterField(
            model_name='team',
            name='about',
            field=django_cryptography.fields.encrypt(markdownx.models.MarkdownxField(blank=True, help_text="<a href='https://en.wikipedia.org/wiki/Markdown'>You can use Markdown</a>", verbose_name='About')),
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='City')),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, verbose_name='Country')),
        ),
        migrations.AlterField(
            model_name='team',
            name='email_address',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
        ),
        migrations.AlterField(
            model_name='team',
            name='postal_code',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=10, verbose_name='Postal code')),
        ),
        migrations.AlterField(
            model_name='team',
            name='province',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='Province')),
        ),
        migrations.AlterField(
            model_name='team',
            name='street',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='Street')),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
    ]
